blank_issues_enabled: false
contact_links:
  - name: OTServ Discord
    url: https://discord.gg/3NxYnyV?utm_source=Github
    about: If you have support and related questions, please get in contact with us via our discord server.